package postfx

// Post-processing presets — named configurations as compile-time constants.
// Apply with pipeline_apply_preset().

Preset :: struct {
	name:          string,
	effects:       Effect_Flags,
	vignette:      Vignette_Params,
	grain:         Grain_Params,
	exposure:      Exposure_Params,
	chrom_abbr:    Chrom_Aberration_Params,
	white_balance: White_Balance_Params,
	color_grading: Color_Grading_Params,
	tonemapper:    Tonemap_Params,
	bloom:         Bloom_Params,
	fxaa:          FXAA_Params,
	dof:           Dof_Params,
	banding:       Banding_Params,
	fog:           Fog_Params,
	motion_blur:   Motion_Blur_Params,
	lut3d:         LUT3D_Params,
}

// All available presets (indexed by Preset_Id).
Preset_Id :: enum {
	Default,
	Subtle,
	Cinematic,
	Vibrant,
	Clean,
	Vintage,
	Matrix,
	BW_Contrast,
	Posterized,
	Retro,
	Analog,
	Channel_GFX,
	Blueprint,
	Nordic_Noir,
	Sony_A7SIII,
}

PRESET_NAMES :: [Preset_Id]string{
	.Default     = "Default",
	.Subtle      = "Subtle",
	.Cinematic   = "Cinematic",
	.Vibrant     = "Vibrant",
	.Clean       = "Clean",
	.Vintage     = "Vintage",
	.Matrix      = "Matrix",
	.BW_Contrast = "BW Contrast",
	.Posterized  = "Posterized",
	.Retro       = "Retro",
	.Analog      = "Analog",
	.Channel_GFX = "Channel GFX",
	.Blueprint   = "Blueprint",
	.Nordic_Noir = "Nordic Noir",
	.Sony_A7SIII = "Sony A7S III",
}

// Presets that depend on unported effects (Banding/Fog/LUT3D). They remain
// selectable for data inspection but their look will be incomplete until the
// matching effect shaders are ported. See docs/postfx-porting-gap-2026-05-19.md.
PRESET_WIP :: [Preset_Id]bool{
	.Default     = false,
	.Subtle      = false,
	.Cinematic   = false,
	.Vibrant     = false,
	.Clean       = false,
	.Vintage     = false,
	.Matrix      = false,
	.BW_Contrast = false,
	.Posterized  = false,
	.Retro       = false,
	.Analog      = false,
	.Channel_GFX = false,
	.Blueprint   = false,
	.Nordic_Noir = false, // Fog implemented (Phase 3 complete)
	.Sony_A7SIII = false, // LUT3D implemented (Phase 5 complete)
}

PRESETS :: [Preset_Id]Preset{
	.Default = {
		name    = "Default",
		effects = {.Exposure},
		vignette = {
			intensity  = DEFAULT_VIGNETTE_INTENSITY,
			smoothness = DEFAULT_VIGNETTE_SMOOTHNESS,
			roundness  = DEFAULT_VIGNETTE_ROUNDNESS,
		},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 1.0, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = DEFAULT_BLOOM_INTENSITY, threshold = DEFAULT_BLOOM_THRESHOLD, soft_threshold = DEFAULT_BLOOM_SOFT_THRESHOLD, radius = DEFAULT_BLOOM_RADIUS},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Subtle = {
		name    = "Subtle",
		effects = {.Exposure, .Tonemap, .Vignette},
		vignette = {intensity = 0.4, smoothness = 0.6, roundness = 1.0},
		grain = {
			intensity            = 0.0,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = 1.0},
		chrom_abbr    = {strength = 0.0},
		white_balance = {temperature = 6500.0, tint = 0.0},
		color_grading = {saturation = 1.0, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = 1.0, toe = 0.1, shoulder = 0.3, black_clip = 0.0, white_clip = 0.0},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Cinematic = {
		name    = "Cinematic",
		effects = {.Exposure, .Tonemap, .Vignette, .Grain, .Bloom, .Color_Grading, .Chrom_Abbr},
		vignette = {intensity = 1.2, smoothness = 0.4, roundness = 0.8},
		grain = {
			intensity            = 0.04,
			intensity_shadows    = 1.2,
			intensity_midtones   = 0.8,
			intensity_highlights = 0.3,
			shadows_max          = 0.12,
			highlights_min       = 0.6,
			texel_size           = 1.5,
		},
		exposure      = {exposure = 1.2},
		chrom_abbr    = {strength = 0.003},
		white_balance = {temperature = 5800.0, tint = 0.0},
		color_grading = {saturation = 0.9, contrast = 1.15, gamma = 0.95, gain = 1.0, offset = -0.01, lift = 0.0},
		tonemapper    = {slope = 1.2, toe = 0.2, shoulder = 0.5, black_clip = 0.01, white_clip = 0.02},
		bloom         = {intensity = 0.3, threshold = 0.8, soft_threshold = 0.6, radius = 1.2},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Vibrant = {
		name    = "Vibrant",
		effects = {.Exposure, .Tonemap, .Bloom, .Color_Grading, .FXAA},
		vignette = {intensity = 0.3, smoothness = 0.8, roundness = 1.0},
		grain = {
			intensity            = 0.0,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = 1.3},
		chrom_abbr    = {strength = 0.0},
		white_balance = {temperature = 6500.0, tint = 0.0},
		color_grading = {saturation = 1.4, contrast = 1.1, gamma = 1.0, gain = 1.05, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = 1.0, toe = 0.1, shoulder = 0.4, black_clip = 0.0, white_clip = 0.0},
		bloom         = {intensity = 0.5, threshold = 0.6, soft_threshold = 0.7, radius = 1.5},
		fxaa          = {subpix = 0.75, edge_threshold = 0.125, edge_threshold_min = 0.063},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Clean = {
		name    = "Clean",
		effects = {.Exposure, .Tonemap, .FXAA},
		vignette = {intensity = 0.0, smoothness = 0.5, roundness = 1.0},
		grain = {
			intensity            = 0.0,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = 1.0},
		chrom_abbr    = {strength = 0.0},
		white_balance = {temperature = 6500.0, tint = 0.0},
		color_grading = {saturation = 1.0, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = 1.0, toe = 0.0, shoulder = 0.0, black_clip = 0.0, white_clip = 0.0},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = 0.75, edge_threshold = 0.125, edge_threshold_min = 0.063},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Vintage = {
		name    = "Vintage",
		effects = {.Vignette, .Grain, .Chrom_Abbr, .Exposure, .Color_Grading},
		vignette = {intensity = 0.7, smoothness = 0.8, roundness = 1.0},
		grain = {
			intensity            = 0.06,
			intensity_shadows    = 1.5,
			intensity_midtones   = 1.0,
			intensity_highlights = 0.5,
			shadows_max          = 0.15,
			highlights_min       = 0.6,
			texel_size           = 1.5,
		},
		exposure      = {exposure = 0.9},
		chrom_abbr    = {strength = 0.02},
		white_balance = {temperature = 5500.0, tint = 0.05},
		color_grading = {saturation = 0.8, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Matrix = {
		name    = "Matrix",
		effects = {.Color_Grading, .Bloom},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = 7500.0, tint = 0.2},
		color_grading = {saturation = 0.5, contrast = 1.2, gamma = 0.9, gain = 1.1, offset = 0.02, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.2, threshold = 0.8, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.BW_Contrast = {
		name    = "BW Contrast",
		effects = {.Color_Grading},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 0.0, contrast = 1.5, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Posterized = {
		name    = "Posterized",
		effects = {.Exposure, .Banding, .FXAA},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 1.5, contrast = 1.5, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = {mode = .Linear, levels = 4.0, dither_strength = 0.0, perceptual_gamma = 1.0, channel_levels = {4.0, 4.0, 4.0}},
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Retro = {
		name    = "Retro",
		effects = {.Exposure, .Banding, .FXAA},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 0.5, contrast = 1.3, gamma = 1.1, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = {mode = .Dithered, levels = 8.0, dither_strength = 1.5, perceptual_gamma = 1.0, channel_levels = {8.0, 8.0, 8.0}},
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Analog = {
		name    = "Analog",
		effects = {.Exposure, .Banding, .FXAA},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 1.0, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = {mode = .Perceptual, levels = 12.0, dither_strength = 0.0, perceptual_gamma = 2.2, channel_levels = {12.0, 12.0, 12.0}},
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Channel_GFX = {
		name    = "Channel GFX",
		effects = {.Exposure, .Banding, .FXAA},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 1.0, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = {mode = .Channel, levels = 256.0, dither_strength = 0.0, perceptual_gamma = 1.0, channel_levels = {8.0, 8.0, 4.0}},
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Blueprint = {
		name    = "Blueprint",
		effects = {.Exposure, .Banding, .FXAA},
		vignette = {intensity = DEFAULT_VIGNETTE_INTENSITY, smoothness = DEFAULT_VIGNETTE_SMOOTHNESS, roundness = DEFAULT_VIGNETTE_ROUNDNESS},
		grain = {
			intensity            = DEFAULT_GRAIN_INTENSITY,
			intensity_shadows    = 1.0,
			intensity_midtones   = 1.0,
			intensity_highlights = 1.0,
			shadows_max          = DEFAULT_GRAIN_SHADOWS_MAX,
			highlights_min       = DEFAULT_GRAIN_HIGHLIGHTS_MIN,
			texel_size           = DEFAULT_GRAIN_TEXEL_SIZE,
		},
		exposure      = {exposure = DEFAULT_EXPOSURE},
		chrom_abbr    = {strength = DEFAULT_CHROM_ABBR_STRENGTH},
		white_balance = {temperature = DEFAULT_WB_TEMP, tint = DEFAULT_WB_TINT},
		color_grading = {saturation = 1.0, contrast = 1.0, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.0},
		tonemapper    = {slope = DEFAULT_TONEMAP_SLOPE, toe = DEFAULT_TONEMAP_TOE, shoulder = DEFAULT_TONEMAP_SHOULDER, black_clip = DEFAULT_TONEMAP_BLACK_CLIP, white_clip = DEFAULT_TONEMAP_WHITE_CLIP},
		bloom         = {intensity = 0.0, threshold = 1.0, soft_threshold = 0.5, radius = 1.0},
		fxaa          = {subpix = DEFAULT_FXAA_SUBPIX, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = {mode = .Luminance, levels = 6.0, dither_strength = 0.0, perceptual_gamma = 1.0, channel_levels = {0.1, 0.4, 0.9}},
		fog           = DEFAULT_FOG_PARAMS,
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Nordic_Noir = {
		name    = "Nordic Noir",
		effects = {.Vignette, .Grain, .Exposure, .Bloom, .Color_Grading, .Chrom_Abbr, .FXAA, .Fog},
		vignette = {intensity = 0.45, smoothness = 0.7, roundness = 0.6},
		grain = {
			intensity            = 0.25,
			intensity_shadows    = 1.3,
			intensity_midtones   = 1.0,
			intensity_highlights = 0.4,
			shadows_max          = 0.15,
			highlights_min       = 0.55,
			texel_size           = 2.0,
		},
		exposure      = {exposure = 0.85},
		chrom_abbr    = {strength = 0.003},
		white_balance = {temperature = 4050.0, tint = -0.04},
		color_grading = {saturation = 0.88, contrast = 1.20, gamma = 1.05, gain = 1.0, offset = 0.0, lift = 0.045},
		tonemapper    = {slope = 0.88, toe = 0.18, shoulder = 0.45, black_clip = 0.0, white_clip = 0.01},
		bloom         = {intensity = 0.09, threshold = 0.80, soft_threshold = 0.55, radius = 2.4},
		fxaa          = {subpix = 0.45, edge_threshold = DEFAULT_FXAA_EDGE_THRESHOLD, edge_threshold_min = DEFAULT_FXAA_EDGE_THRESHOLD_MIN},
		dof           = DEFAULT_DOF_PARAMS,
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = {density = 0.022, start = 3.5, height_falloff = 0.018, max_opacity = 0.85, color = {0.10, 0.16, 0.22}},
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = DEFAULT_LUT3D_PARAMS,
	},
	.Sony_A7SIII = {
		name    = "Sony A7S III",
		effects = {.Vignette, .Grain, .Auto_Exposure, .Bloom, .Color_Grading, .FXAA, .Dof, .LUT3D},
		vignette = {intensity = 0.35, smoothness = 0.65, roundness = 0.8},
		grain = {
			intensity            = 0.018,
			intensity_shadows    = 1.1,
			intensity_midtones   = 1.0,
			intensity_highlights = 0.5,
			shadows_max          = 0.1,
			highlights_min       = 0.55,
			texel_size           = 1.2,
		},
		exposure      = {exposure = 1.0},
		chrom_abbr    = {strength = 0.0},
		white_balance = {temperature = 6500.0, tint = 0.0},
		color_grading = {saturation = 1.04, contrast = 1.02, gamma = 1.0, gain = 1.0, offset = 0.0, lift = 0.015},
		tonemapper    = {slope = 0.92, toe = 0.12, shoulder = 0.38, black_clip = 0.0, white_clip = 0.005},
		bloom         = {intensity = 0.035, threshold = 0.85, soft_threshold = 0.5, radius = 1.8},
		fxaa          = {subpix = 0.75, edge_threshold = 0.125, edge_threshold_min = 0.0625},
		dof           = {focal_distance = 16.0, focal_range = 4.0, bokeh_scale = 12.0, anamorphic_ratio = 2.0},
		banding       = DEFAULT_BANDING_PARAMS,
		fog           = {density = 0.0, start = 10.0, height_falloff = 0.1, max_opacity = 0.9, color = {0.5, 0.6, 0.7}},
		motion_blur   = DEFAULT_MOTION_BLUR_PARAMS,
		lut3d         = {intensity = 1.0},
	},
}

// Apply a preset to the pipeline (overwrites all params and active effects).
pipeline_apply_preset :: proc(p: ^Pipeline, id: Preset_Id) {
	presets := PRESETS
	preset := presets[id]
	p.active_effects = preset.effects
	p.debug_split    = {}  // Clear all A/B split state
	p.cached_debug   = {}  // Clear cached debug views
	p.cached_split   = {}  // Clear cached split state
	p.vignette       = preset.vignette
	p.grain          = preset.grain
	p.exposure       = preset.exposure
	p.chrom_abbr     = preset.chrom_abbr
	p.white_balance  = preset.white_balance
	p.color_grading  = preset.color_grading
	p.tonemapper     = preset.tonemapper
	p.bloom          = preset.bloom
	p.fxaa           = preset.fxaa
	p.dof            = preset.dof
	p.banding        = preset.banding
	p.fog            = preset.fog
	p.motion_blur    = preset.motion_blur
	p.lut3d          = preset.lut3d
	p.ubo_dirty      = true
}
