package scene

// --- GENERATED FILE — DO NOT EDIT MANUALLY ---
// Generated by tools/codegen from verification/EnvManagerVerification.tla

Transition_State :: enum {
	Idle,
	Loading,
	Wait_IBL,
	Fade_Out,
	Fade_In,
}

IBL_State :: enum {
	Idle,
	Upload_Texture,
	Upload_Progressive,
	Generate_Mipmaps,
	Luminance,
	Specular_Init,
	Specular_Mips,
	Irradiance,
	Done,
}

IS_TRANSITION_VALID : [Transition_State][Transition_State]bool = {
	.Idle = {
		.Idle = true,
		.Loading = true,
		.Wait_IBL = false,
		.Fade_Out = false,
		.Fade_In = false,
	},
	.Loading = {
		.Idle = true,
		.Loading = true,
		.Wait_IBL = true,
		.Fade_Out = false,
		.Fade_In = false,
	},
	.Wait_IBL = {
		.Idle = true,
		.Loading = false,
		.Wait_IBL = true,
		.Fade_Out = true,
		.Fade_In = true,
	},
	.Fade_Out = {
		.Idle = true,
		.Loading = false,
		.Wait_IBL = false,
		.Fade_Out = true,
		.Fade_In = true,
	},
	.Fade_In = {
		.Idle = true,
		.Loading = false,
		.Wait_IBL = false,
		.Fade_Out = false,
		.Fade_In = true,
	},
}

IS_IBL_VALID : [IBL_State][IBL_State]bool = {
	.Idle = {
		.Idle = true,
		.Upload_Texture = true,
		.Upload_Progressive = false,
		.Generate_Mipmaps = false,
		.Luminance = false,
		.Specular_Init = false,
		.Specular_Mips = false,
		.Irradiance = false,
		.Done = false,
	},
	.Upload_Texture = {
		.Idle = true,
		.Upload_Texture = true,
		.Upload_Progressive = true,
		.Generate_Mipmaps = false,
		.Luminance = false,
		.Specular_Init = false,
		.Specular_Mips = false,
		.Irradiance = false,
		.Done = false,
	},
	.Upload_Progressive = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = true,
		.Generate_Mipmaps = true,
		.Luminance = false,
		.Specular_Init = false,
		.Specular_Mips = false,
		.Irradiance = false,
		.Done = false,
	},
	.Generate_Mipmaps = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = false,
		.Generate_Mipmaps = true,
		.Luminance = true,
		.Specular_Init = false,
		.Specular_Mips = false,
		.Irradiance = false,
		.Done = false,
	},
	.Luminance = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = false,
		.Generate_Mipmaps = false,
		.Luminance = true,
		.Specular_Init = true,
		.Specular_Mips = false,
		.Irradiance = false,
		.Done = false,
	},
	.Specular_Init = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = false,
		.Generate_Mipmaps = false,
		.Luminance = false,
		.Specular_Init = true,
		.Specular_Mips = true,
		.Irradiance = false,
		.Done = false,
	},
	.Specular_Mips = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = false,
		.Generate_Mipmaps = false,
		.Luminance = false,
		.Specular_Init = false,
		.Specular_Mips = true,
		.Irradiance = true,
		.Done = false,
	},
	.Irradiance = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = false,
		.Generate_Mipmaps = false,
		.Luminance = false,
		.Specular_Init = false,
		.Specular_Mips = false,
		.Irradiance = true,
		.Done = true,
	},
	.Done = {
		.Idle = true,
		.Upload_Texture = false,
		.Upload_Progressive = false,
		.Generate_Mipmaps = false,
		.Luminance = false,
		.Specular_Init = false,
		.Specular_Mips = false,
		.Irradiance = false,
		.Done = true,
	},
}

env_manager_validate_transition :: proc(from, to: Transition_State) -> bool {
	return IS_TRANSITION_VALID[from][to]
}

env_manager_validate_ibl :: proc(from, to: IBL_State) -> bool {
	return IS_IBL_VALID[from][to]
}

env_manager_validate_invariants :: proc(transition_state: Transition_State, ibl_state: IBL_State) {
	// Invariant SafeTransition: IBL state machine must remain Idle unless a transition is active
	if transition_state == .Idle {
		assert(ibl_state == .Idle, "Invariant Violation (SafeTransition): IBL state machine must remain Idle unless a transition is active")
	}
}
